### ISSUE TITLE
cannot get it to work

### ISSUE THREAD

**Issue by francescor** [GMaissa/ansible-role-ezpublish5#1]
Cannot get it to work (with debian/jessie64, nor ubuntu/trusty64)

what vagrant box should I choose?

(thanks for what you are doing, it's great!)

**Comment by francescor** [comment]
oh, I see now in https://github.com/GMaissa/ansible-role-ezpublish5/blob/master/tests/Vagrantfile the box you've used.  I'll try with those.

**Comment by GMaissa** [comment]
Hi

Just in case, I created a gist to show a complete example that might help : https://gist.github.com/GMaissa/653a5110a6b4a4200d27

Cheers,

**Comment by francescor** [comment]
oh, great! this will help a lot!
thanks!
